### ISSUE TITLE
Build fails on arm64 (rpi4)

### ISSUE THREAD

**Issue by fuzebox1** [bodoni/font#3]
I am attempting to install alacritty on my raspberry pi 4. Upon compiling font (tried 0.1.0 and 0.3.0) and i get error E0308: Mismatched types.
On line 339 in mod.rs: expected i32, found i64. Compiler help says you can convert an i64 to i32 and panic if the converted value wouldn't fit.

**Comment by fuzebox1** [comment]
Alacritty uses the 0.1.0 package. It has the error at line 367.
The rpi4 is armv7l. Im running Arch linux arm.

**Comment by IvanUkhov** [comment]
Hello, does it fail in this crate or in some of the dependencies? There is no `mod.rs` with that many lines.
