### ISSUE TITLE
thread 'main' panicked at 'not implemented' for some fonts

### ISSUE THREAD

**Issue by johnoneil** [bodoni/font#4]
```
Font::open(path).unwrap()
```
Fails with "not implemented" panic when opening google font `NotoSansJP-Regular.otf` and others.

**Comment by IvanUkhov** [comment]
Added a (failing) test for parsing all Google Fonts:

https://github.com/bodoni/workbench/blob/main/Makefile#L17

**Comment by IvanUkhov** [comment]
The font you mentioned seems to deviate from the specification. Filed a bug report:

https://github.com/google/fonts/issues/5620

**Comment by IvanUkhov** [comment]
Added a feature to ignore the violation:

https://github.com/bodoni/postscript/blob/main/Cargo.toml#L18
